server {
    listen 5173;
    root /usr/share/nginx/html;
    index index.html;

    # Маршрутизація для Single Page Application (SPA)
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Кешування статичних файлів для підвищення продуктивності
    location ~* \.(js|css|png|jpg|svg|ico|woff2)$ {
        expires 30d;
        add_header Cache-Control "public, immutable";
    }
}
